### ISSUE TITLE
yellow field

### ISSUE THREAD

**Issue by Mainmaster01** [plasmoapp/pv-addon-discs#10]
Hello, the add-on works great, but I would like the yellow field that shows the radius of the sound not to be visible. Very annoying on the server.
![2023-06-14_13 44 58](https://github.com/plasmoapp/pv-addon-discs/assets/136564266/519480a7-2f3a-4a4d-9875-6993e65f386e)

**Comment by Apehum** [comment]
Added in [pv-addon-discs v1.0.6](https://modrinth.com/plugin/pv-addon-discs/version/1.0.6)
