### ISSUE TITLE
YouTube links that start the video at a certain point don't work.

### ISSUE THREAD

**Issue by MagmaBro123** [plasmoapp/pv-addon-discs#14]
Title. The "?t=34" part of a YT link is ignored, and any track on YT is always played from the start.

**Comment by KPidS** [comment]
This is more of an issue with the library we use to play audio from YouTube: https://github.com/Walkyst/lavaplayer-fork
Not sure if it's even an issue though, and I don't think that it's something that I would like to be fixed.

**Comment by MagmaBro123** [comment]
Would be nice so you don't have to download the video and edit it manually.
