### ISSUE TITLE
The addon does not start

### ISSUE THREAD

**Issue by Xkall2** [plasmoapp/pv-addon-discs#16]
[pv-addon-discs] Plugin pv-addon-discs v1.0.4 has failed to register events for class su.plo.voice.discs.event.ForbidGrindstoneListener because org/bukkit/event/inventory/PrepareGrindstoneEvent does not exist.

**Comment by Xkall2** [comment]
...

**Comment by Xkall2** [comment]
...

**Comment by Apehum** [comment]
What version of mc are you using? The addon only supports 1.19.2+ PaperMC

**Comment by Xkall2** [comment]
I used paper 1.19.2-307
