### ISSUE TITLE
Бесконечное зацикливание трека

### ISSUE THREAD

**Issue by phys1cs27** [plasmoapp/pv-addon-discs#18]
Если пластинку много раз сунуть в проигрыватель, она забагуется (баг ванильного майнкрафта), тем самым вызовет бесконечный шум.
![image](https://github.com/plasmoapp/pv-addon-discs/assets/95995512/136fe15d-0cb8-4750-9137-6a57adfd5baf)
Версия сервера PurPur 1.20.1

**Comment by Apehum** [comment]
Должно быть пофикшено в 1.0.5:
https://modrinth.com/plugin/pv-addon-discs/version/1.0.5
