### ISSUE TITLE
Зацикливание трека

### ISSUE THREAD

**Issue by foxya27** [plasmoapp/pv-addon-discs#21]
Как увидеть баг, записываем трек длиннее 4 минут, вставляем в проигрыватель, ждем минуты 3.5, достаем пластинку, трек багуется и продолжает играть, чтобы отключить его нужно либо сломать проигрыватель, вставить заного пластинку.

**Comment by Shepelzz** [comment]
ты бы на инглиш перевел, а то ждать будешь еще не один год.

**Comment by Apehum** [comment]
Извиняюсь за очень поздний ответ, это должно быть пофикшено в пререлизе: https://github.com/plasmoapp/pv-addon-discs/releases/tag/1.0.6

**Comment by Apehum** [comment]
https://modrinth.com/plugin/pv-addon-discs/version/1.0.6
