### ISSUE TITLE
Не работает разрешение pv.addon.discs.burn

### ISSUE THREAD

**Issue by DenGo196** [plasmoapp/pv-addon-discs#34]
Хотел добавить возможность всем игрокам добавлять музыку, нашел здесь в ответах, через лакпермс добавить разрешение pv.addon.discs.burn, но игрокам все ровно пишет, что нет прав.

**Comment by Apehum** [comment]
Скорее всего права неправильно настроены, проверь права через `/lp user <user> permission check pv.addon.discs.burn`. Если там `true`, то переоткрой это issue
