### ISSUE TITLE
Video returbed by YouTube isn't what eas requested

### ISSUE THREAD

**Issue by McRa1nY** [plasmoapp/pv-addon-discs#43]
Just recently I got this error. All libraries and plugins are installed to the latest version, the error came out of nowhere. What to do? How to fix?
![IMG_20240330_185510_916~2](https://github.com/plasmoapp/pv-addon-discs/assets/118021312/b06bbb3f-fbc6-45ad-9984-973bbf7b78b8)

**Comment by McRa1nY** [comment]
This error occurs when you insert a record into the jukebox, and also when you burn the record onto a new track.

**Comment by mad4me** [comment]
Same thing happening, no idea how to fix, issues this error: 

![image](https://github.com/plasmoapp/pv-addon-discs/assets/54853465/13a4a682-cfd0-4d0b-9486-d512ac0a1fcc)

**Comment by Apehum** [comment]
Try to use pv-addon-lavaplayer prerelease: https://github.com/plasmoapp/pv-addon-lavaplayer-lib/releases/tag/1.0.8

**Comment by mad4me** [comment]
> Try to use pv-addon-lavaplayer prerelease: https://github.com/plasmoapp/pv-addon-lavaplayer-lib/releases/tag/1.0.8

It worked, thank you!

**Comment by McRa1nY** [comment]
> Try to use pv-addon-lavaplayer prerelease: https://github.com/plasmoapp/pv-addon-lavaplayer-lib/releases/tag/1.0.8

Thank you!
