### ISSUE TITLE
Ютуб не принимает ссылки

### ISSUE THREAD

**Issue by Lisatot** [plasmoapp/pv-addon-discs#44]
[Ютуб.txt](https://github.com/plasmoapp/pv-addon-discs/files/14816578/default.txt)
![Screenshot_1](https://github.com/plasmoapp/pv-addon-discs/assets/46389704/f4aae908-1a97-4894-b10c-f57ff56d1dfa)
На сервере стоит PlasmoVoice-Paper-2.0.8, pv-addon-discs-1.0.6, pv-addon-lavaplayer-lib-1.0.7, версия ядра 1.20.2. С какого-то промежутка времени перестали работать диски, не записывается трек, при этом сам плазмовойс работает. Прилагаю скриншот сообщения и текстовик логов

**Comment by Apehum** [comment]
Используй https://github.com/plasmoapp/pv-addon-lavaplayer-lib/releases/tag/1.0.8. Если остались проблемы с этой версией, то открой issue в https://github.com/plasmoapp/pv-addon-lavaplayer-lib
