### ISSUE TITLE
Ошибка с YouTube помогите пожалуйста. Error from YouTube, please help.

### ISSUE THREAD

**Issue by RATcraftGames** [plasmoapp/pv-addon-discs#47]
Ошибка: Не получилось получить трек: Video returned by YouTube isn't what was requested.
Error: The track could not be found: The video returned by YouTube does not match the requested one.

Пожалуйста как можно быстрее, потому что мне надо открыть сервер, а игроки очень хотят эту функцию с кастомной музыкой.

Please, as soon as possible, because I need to open the server, and the players really want this feature with custom music.

https://github.com/plasmoapp/pv-addon-discs/assets/166902642/6603e0fa-8c6d-44b1-a01d-8a8fcbce7d72

**Comment by Apehum** [comment]
https://github.com/plasmoapp/pv-addon-lavaplayer-lib/releases/tag/1.0.8

**Comment by RATcraftGames** [comment]
Я сейчас это проверю но он у меня стоял может нужна именно эта версия.

I'll check it out now, but I had it standing, maybe this version is needed.

**Comment by RATcraftGames** [comment]
Всё заработало спасибо!

Everything worked thanks!
