### ISSUE TITLE
Can’t burn disc | Video returned by Youtube isn’t what was requested

### ISSUE THREAD

**Issue by booby1545** [plasmoapp/pv-addon-discs#48]
Minecraft version 1.20.4
Server Core: Paper
Tested on versions 1.0.5, 1.0,4.
Disc search works perfectly, but burn not at all. (YES I issued it with disc in my hand)

![image](https://github.com/plasmoapp/pv-addon-discs/assets/107137294/1f287585-e8c9-4628-a5b9-252fecc45e88)
[latest.log](https://github.com/plasmoapp/pv-addon-discs/files/14972111/latest.log)

**Comment by Apehum** [comment]
Use prerelease of the lavaplayer addon: https://github.com/plasmoapp/pv-addon-lavaplayer-lib/releases/tag/1.0.8

**Comment by Apehum** [comment]
Fixed in [pv-addon-discs v1.0.6](https://modrinth.com/plugin/pv-addon-discs/version/1.0.6) with [pv-addon-lavaplayer-lib v1.0.8](https://modrinth.com/plugin/pv-addon-lavaplayer-lib/version/1.0.8)
