### ISSUE TITLE
Add the ability to insert any links just to audio

### ISSUE THREAD

**Issue by Ghoster12154** [plasmoapp/pv-addon-discs#54]
Добавьте возможность вставлять любые ссылки просто на аудио
Например http://127.0.0.1/files/uploaded_files/1.mp3
Я пробовал и говорит, что не удалось получить трек
Это больше просьба, а не баг или проблема

Add the ability to insert any links just to audio
For example http://127.0.0.1/files/uploaded_files/1.mp3
I tried and says I couldn't get the track
This is more of a request, not a bug or a problem.

**Comment by Apehum** [comment]
Прямые ссылки поддерживаются, просто по умолчанию включен вайтлист на ссылки для безопасности.
Добавь в `http_source.whitelist` свой домен/айпи, с которого ты хочешь загружать треки и все должно работать:
![image](https://github.com/plasmoapp/pv-addon-discs/assets/36326454/a208083c-f508-4eab-b183-a691e166622f)

**Comment by Ghoster12154** [comment]
Спасибо за помощь, у вас очень отзывчивая поддержка
