### ISSUE TITLE
Error: "Sign in to confirm you`re not a bot"

### ISSUE THREAD

**Issue by Roninore** [plasmoapp/pv-addon-discs#57]
![image](https://github.com/plasmoapp/pv-addon-discs/assets/76597977/9b8a54b5-d4e6-4cbd-aca3-681d0b97fad3)

``` 
This server is running Paper version git-Paper-496 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 7ac24a1 
on ver/1.20.4)
```
```
pv-addon-discs: 1.0.6
pv-addon-lavaplayer-lib: 1.0.9
```
Error when i try to use /disc burn command. In console no errors yet.

I'm ready to provide more information of my issue.

**Comment by Roninore** [comment]
Apparently I need to provide the plugin with an authorization cookie or authorization data so that it can use the account to access YouTube. But it seems that there is no such possibility

**Comment by Roninore** [comment]
The problem is still relevant, is there an updates?

**Comment by apehum** [comment]
https://github.com/plasmoapp/pv-addon-discs?tab=readme-ov-file#sign-in-to-confirm-youre-not-a-bot--please-sign-in-using-youtube
