### ISSUE TITLE
Direct links aren't working

### ISSUE THREAD

**Issue by teleportx** [plasmoapp/pv-addon-discs#6]
![image](https://github.com/plasmoapp/pv-addon-discs/assets/77507478/599ad1d2-32ab-4207-add4-6eef39fcd655)
When trying to use a link to a audio file, it throws an error: `Failed to get the track: No matches`

**Comment by KPidS** [comment]
Либо ссылка кривая, либо сервер не может сделать запрос на сайт (проблема со стороны сервера или со стороны сайта), либо в конфиге включён вайтлист доменов и этого домена нет в списке
