### ISSUE TITLE
ошибка : no matches

### ISSUE THREAD

**Issue by fervauk** [plasmoapp/pv-addon-discs#65]
плагин был загружен, показывается как рабочий но при попытке прописать музыку на пластинку выдаёт ошибку 
![image](https://github.com/plasmoapp/pv-addon-discs/assets/174867697/4e5f42f4-5129-4e6f-b2f4-e59d4f688e93)

**Comment by apehum** [comment]
Use the latest alpha versions:
- https://modrinth.com/plugin/pv-addon-discs/version/1.1.3
- https://modrinth.com/plugin/pv-addon-lavaplayer-lib/version/1.1.1

If you still have any issues, please open a new issue and provide server logs.
