### ISSUE TITLE
An internal error occurred while attempting to tab-complete this command

### ISSUE THREAD

**Issue by m0rt1ferum** [plasmoapp/pv-addon-discs#66]
При написании ютуб ссылки в команду /disc burn выдаёт данную ошибку
![javaw_TEoNHsIfxK](https://github.com/plasmoapp/pv-addon-discs/assets/175070526/d299acd3-c393-4d92-af14-fc91d837f9d3)
![javaw_sIMv8WzKQb](https://github.com/plasmoapp/pv-addon-discs/assets/175070526/bbe4fa13-5697-424e-b516-3e18ee3112f9)

**Comment by Apehum** [comment]
Обнови ProtocolLib
