### ISSUE TITLE
Error when downloading YouTube music, on all versions of the plugin

### ISSUE THREAD

**Issue by EraserXol** [plasmoapp/pv-addon-discs#67]
Error when downloading YouTube music, on all versions of the plugin
![image](https://github.com/plasmoapp/pv-addon-discs/assets/129385106/5fd9667d-f549-483c-85f5-1f9983efb5f4)

**Comment by Apehum** [comment]
Update pv-addon-lavaplayer-lib to [v1.0.10](https://modrinth.com/plugin/pv-addon-lavaplayer-lib/version/1.0.10)
