### ISSUE TITLE
 records don't work

### ISSUE THREAD

**Issue by Mainmaster01** [plasmoapp/pv-addon-discs#69]
![Screenshot (22)](https://github.com/user-attachments/assets/f0b22709-bcfc-49a6-bc4d-74ebad44eff3)
help

**Comment by Apehum** [comment]
Update pv-addon-lavaplayer-lib to [v1.0.10](https://modrinth.com/plugin/pv-addon-lavaplayer-lib/version/1.0.10)

**Comment by Apehum** [comment]
Make sure ProtocolLib is installed and working properly
