### ISSUE TITLE
The audio won't stop

### ISSUE THREAD

**Issue by AzimovUA** [plasmoapp/pv-addon-discs#7]
If you pull the disc out of the jukebox, or break the jukebox, then the audio does not stop.

There is no logs in the console.

Info about server:
Purpur 1.19.2
pv-addon-discs 1.0.2 (tried 1.0.1)
pv-addon-lavaplayer-lib 1.0.4 (tried 1.0.3)
PlasmoVoice-Paper 2.0.4

Default config for all plugins, core almost default.

<img src="https://github.com/plasmoapp/pv-addon-discs/assets/59807075/9136ff47-7e52-473d-b6d8-22a1c2adc167" width="250" height="200">

<img src="https://github.com/plasmoapp/pv-addon-discs/assets/59807075/870a1aa7-3ed5-42bd-9e17-4f832ae338df" width="250" height="200">

**Comment by KPidS** [comment]
Can you test it with pure default Purpur and also Paper?

**Comment by AzimovUA** [comment]
> Can you test it with pure default Purpur and also Paper?

I installed Paper 1.19.2 and deleted all plugins except ProtocolLib (616), PalsmoVoice, pv-addon-discs, and pv-addon-lavaplayer-lib. However, I am still experiencing the same problem. I don't think there's a need to test Purpur since it appears to have the same issue.

**Comment by KPidS** [comment]
This happened because in 1.19.4 the API related to Jukebox changed. The plugin is updated to use the latest API. You can either use the previous version of the plugin or use the latest version of Minecraft.

**Comment by KPidS** [comment]
Turns out this issue is also present in 1.19.4. No idea when and why it happened, and why there wasn't such an issue before, but I will release a fix soon. Still not sure if it will work on 1.19.2 though

**Comment by KPidS** [comment]
Fixed in 1.0.3 https://modrinth.com/plugin/pv-addon-discs/version/1.0.3

**Comment by phys1cs27** [comment]
@KPidS В 1.0.4 проблема появилась, когда два человека одновременно достали пластинку, очень нужен фикс ...

**Comment by phys1cs27** [comment]
Или возможность заблокировать видео/стримы продолжительностью больше часа
