### ISSUE TITLE
Error: "Sign in to confirm you`re not a bot"

### ISSUE THREAD

**Issue by EBEN-dev-afk** [plasmoapp/pv-addon-discs#71]
![image](https://github.com/user-attachments/assets/2cc2fd85-32eb-4c4d-a068-0a79b18a038d)
![image](https://github.com/user-attachments/assets/c8ecddb0-b623-4c8b-8ad5-fa2ff6218a2d)
```
pv-addon-discs: 1.0.8
pv-addon-lavaplayer-lib: 1.0.10
```

```
This server is running Paper version git-Paper-174 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: c9cd94f)
```

**Comment by Energobro** [comment]
can confirm

**Comment by TheStepashich** [comment]
This is indeed a problem. I have the same! Tried to use VPN, as well as without it. 
The problem is not solved simply so. 

On this problem much is written, but not on this particular addon, but in general about things to get audio from YouTube..

`Current Purpur Version: 1.21-2269-65d3665 (MC: 1.21)*`
`plugin PlasmoVoice v2.0.10`
`plugin pv-addon-discs v1.0.7`
`plugin pv-addon-lavaplayer-lib v1.0.10`

It's because of YouTube, as best I can figure. It was working before.

**Comment by TheRa1nY** [comment]
I have the same problem.

**Comment by PadowYT2** [comment]
You need to use the beta version of pv-addon-discs & pv-addon-lavaplayer-lib and I recommend joining the [Discord Server](https://discord.com/invite/uueEqzwCJJ) if you need further help (please close the issue)

**Comment by EBEN-dev-afk** [comment]
> ![image](https://private-user-images.githubusercontent.com/174366327/349786452-2cc2fd85-32eb-4c4d-a068-0a79b18a038d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4OTE2NTUsIm5iZiI6MTcyMjg5MTM1NSwicGF0aCI6Ii8xNzQzNjYzMjcvMzQ5Nzg2NDUyLTJjYzJmZDg1LTMyZWItNGM0ZC1hMDY4LTBhNzliMThhMDM4ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNVQyMDU1NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMjkyOGM1YzcwNjYyODI3ZjdlMTAxNWQ1ODAyOGViMmFhOTkxZmY5NjFiOWI0YzYwZGY0YmFlMTVkMGJkZDk4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.L4OCxTiJtdhgOrcbFGk5Ru12Y9UzKEzzTAaoHYv_BhY) ![image](https://private-user-images.githubusercontent.com/174366327/349786473-c8ecddb0-b623-4c8b-8ad5-fa2ff6218a2d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4OTE2NTUsIm5iZiI6MTcyMjg5MTM1NSwicGF0aCI6Ii8xNzQzNjYzMjcvMzQ5Nzg2NDczLWM4ZWNkZGIwLWI2MjMtNGM4Yi04YWQ1LWZhMmZmNjIxOGEyZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNVQyMDU1NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZWJhNDcxM2QwYjc2MjVlZTdmM2U0YjQ0N2ViMTUwNzJlMzQxNGE1OWQ2ZDJmNTE3MmVjZDgzNDJjOWZmOGNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BsSO74LWTzTGSa2sA78_RKaCsECYyVGd2_FUd3CqRko)
> 
> ```
> pv-addon-discs: 1.0.8
> pv-addon-lavaplayer-lib: 1.0.10
> ```
> 
> ```
> This server is running Paper version git-Paper-174 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: c9cd94f)
> ```
