### ISSUE TITLE
An internal error occurred while attempting to tab-complete this command пишит эту фигню при попытке продолжить команду на запись 

### ISSUE THREAD

**Issue by ROKBI89900** [plasmoapp/pv-addon-discs#72]
![image](https://github.com/user-attachments/assets/cdb08bce-8cb0-4527-aa3c-874ce9790703)

**Comment by ROKBI89900** [comment]
![image](https://github.com/user-attachments/assets/9336f380-e95d-45fb-8246-29c0e957531a)
мои плагины на сервере

**Comment by PadowYT2** [comment]
Не знаю починил ли ты, но нужны логи, и еще лучше зайди на [Discord сервер](https://discord.com/invite/uueEqzwCJJ)

**Comment by apehum** [comment]
Use the latest alpha versions:
- https://modrinth.com/plugin/pv-addon-discs/version/1.1.3
- https://modrinth.com/plugin/pv-addon-lavaplayer-lib/version/1.1.1

If you still have any issues, please open a new issue and provide server logs.
