### ISSUE TITLE
"StandaloneCoroutine was cancelled"

### ISSUE THREAD

**Issue by MrVINIK** [plasmoapp/pv-addon-discs#73]
ru: Вставляю диск в проигрыватель, а он назад выходит и пишет снизу StandaloneCoroutine was cancelled
en: I insert the disc into the player, and he goes back out and writes from the bottom StandaloneCoroutine was cancelled
![изображение](https://github.com/user-attachments/assets/f02f730d-2be1-4b4c-b451-32b198af5813)

**Comment by apehum** [comment]
Use the latest alpha versions:
- https://modrinth.com/plugin/pv-addon-discs/version/1.1.3
- https://modrinth.com/plugin/pv-addon-lavaplayer-lib/version/1.1.1

If you still have any issues, please open a new issue and provide server logs.
