### ISSUE TITLE
bug "Sign in to confirm you're not a bot"

### ISSUE THREAD

**Issue by TheRa1nY** [plasmoapp/pv-addon-discs#75]
![image](https://github.com/user-attachments/assets/7a6d26e8-68dc-4e43-92f4-1aefd28a66d4)

records cannot be burned to new music from YouTube, a bug. How to fix it?

**Comment by TheRa1nY** [comment]
![image](https://github.com/user-attachments/assets/cb2798e7-2254-4213-a93a-2e85b58c598e)

**Comment by PadowYT2** [comment]
You need to use the beta version of pv-addon-discs & pv-addon-lavaplayer-lib and I recommend joining the [Discord Server](https://discord.com/invite/uueEqzwCJJ) if you need further help (please close the issue)

**Comment by TheRa1nY** [comment]
> You need to use the beta version of pv-addon-discs & pv-addon-lavaplayer-lib and I recommend joining the [Discord Server](https://discord.com/invite/uueEqzwCJJ) if you need further help (please close the issue)

can you send these beta versions?

**Comment by TheRa1nY** [comment]
oh, nothin, i download beta versions. Thanks
