### ISSUE TITLE
Audio stream doubles if you take disc out

### ISSUE THREAD

**Issue by AzimovUA** [plasmoapp/pv-addon-discs#8]
Audio stream doubles if you take disc out, when audio still "Loading..." from the source, and place again in jukebox. You can start infinite streams with this, that causes absolute noise. Probably related to #7 issue.

There is no logs in the console.

Info about server:
Purpur 1.19.2
pv-addon-discs 1.0.2
pv-addon-lavaplayer-lib 1.0.4
PlasmoVoice-Paper 2.0.4

Default config for all plugins, core almost default.

No screenshots needed.

**Comment by KPidS** [comment]
Same as #7
